In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn
import statistics
import math
from scipy.stats import poisson,skellam

world_cup_matches = pd.read_csv("C:\\Users\\ianfr\\Documents\\dev\\inteligencia-computacional\\dataset\\results.csv")
world_cup_matches['year'] = world_cup_matches['date'].str[:4].astype(int)
world_cup_matches['month'] = world_cup_matches['date'].str[5:7].astype(int)
world_cup_matches['day'] = world_cup_matches['date'].str[8:].astype(int)
world_cup_matches = world_cup_matches[['home_team', 'home_score', 'away_score', 'away_team', 'tournament', 'year', 'month', 'day']]
world_cup_matches = world_cup_matches[(world_cup_matches.year) >= 2015]
world_cup_matches = world_cup_matches[(world_cup_matches.year) <= 2018]

wc_teams = ['Russia', 'Brazil', 'Australia', 'Iran', 'Japan', 'Saudi Arabia', 'South Korea', 'Egypt', 'Morocco', 'Nigeria', 'Senegal', 'Tunisia', 'Costa Rica', 'Mexico', 'Panama', 'Argentina', 'Colombia', 'Peru', 'Uruguay', 'Belgium', 'Croatia', 'Denmark', 'England', 'France', 'Germany', 'Iceland', 'Poland', 'Portugal', 'Serbia', 'Spain', 'Sweden', 'Switzerland']
#teams.sort()
#world_cup_matches = world_cup_matches[world_cup_matches.home_team.isin(teams) | world_cup_matches.away_team.isin(teams)]

world_cup_matches.head()

,home_team,home_score,away_score,away_team,tournament,year,month,day
36609,Bahrain,1,0,Jordan,Friendly,2015,1,4
36610,Iran,1,0,Iraq,Friendly,2015,1,4
36611,South Korea,2,0,Saudi Arabia,Friendly,2015,1,4
36612,South Africa,1,0,Zambia,Friendly,2015,1,4
36613,China PR,4,1,Oman,Friendly,2015,1,5

In [8]:
world_cup_matches.describe()

        home_score   away_score         year        month          day
count  3742.000000  3742.000000  3742.000000  3742.000000  3742.000000
mean      1.573223     1.084714  2016.444949     7.070551    15.049973
std       1.569680     1.285719     1.113711     3.190779     8.879508
min       0.000000     0.000000  2015.000000     1.000000     1.000000
25%       0.000000     0.000000  2015.000000     5.000000     8.000000
50%       1.000000     1.000000  2016.000000     7.000000    13.000000
75%       2.000000     2.000000  2017.000000    10.000000    23.750000
max      15.000000    12.000000  2018.000000    12.000000    31.000000

In [16]:
teams2 = world_cup_matches['home_team'].unique().tolist()
teams3 = world_cup_matches['away_team'].unique().tolist()
tournaments = world_cup_matches['tournament'].unique().tolist()
print(tournaments)
game_weight = {'Friendly': 1, 'FIFA World Cup qualification': 2.5, 'UEFA Euro': 2.5, 'Copa América': 2.5, 'UEFA Nations League': 2.5, 'Oceania Nations Cup': 2.5,
              'Confederations Cup': 3, 'FIFA World Cup': 4}

teams = list(set(teams2).union(set(teams3)))
data = {'Team': teams, 'AttackForce': [0 for i in range(len(teams))], 'DefenseForce': [0 for i in range(len(teams))]}
stats = pd.DataFrame(data)

for time in teams:
    team_goals = 0.0
    conceded_goals = 0.0
    team_matches = 0.0
    time_model = world_cup_matches[(world_cup_matches['home_team'] == time) | (world_cup_matches['away_team'] == time)]
    #print(time_model)
    for index, row in time_model.iterrows():
        time_factor = math.exp(-(2018 - row['year'])/3)
        
        if row['tournament'] in game_weight:
            game_weight_factor = game_weight[row['tournament']]
        else:
            game_weight_factor = 2
        #print(game_weight_factor)
        if row['home_team'] == time:
            team_goals += row['home_score'] * time_factor * game_weight_factor
            conceded_goals += (row['away_score'] * time_factor) / game_weight_factor

        if row['away_team'] == time:
            team_goals += row['away_score'] * time_factor * game_weight_factor
            conceded_goals += (row['home_score'] * time_factor) / game_weight_factor
            
        team_matches += 1
        
    
    if conceded_goals != 0 and team_goals != 0:
        stats.loc[stats['Team'] == time, 'AttackForce'] = team_goals/(team_matches)
        stats.loc[stats['Team'] == time, 'DefenseForce'] = (team_matches/(conceded_goals))
    else:
        print(time)
        stats = stats[stats['Team'] != time]
        world_cup_matches = world_cup_matches[world_cup_matches['home_team'] != time]
        world_cup_matches = world_cup_matches[world_cup_matches['away_team'] != time]
    
stats2 = stats.set_index('Team')

print(stats2)

world_cup_matches['HomeAttack'] = [0.0 for i in range(len(world_cup_matches))]
world_cup_matches['HomeDefence'] = [0.0 for i in range(len(world_cup_matches))]
world_cup_matches['AwayAttack'] = [0.0 for i in range(len(world_cup_matches))]
world_cup_matches['AwayDefence'] = [0.0 for i in range(len(world_cup_matches))]

for index, row in world_cup_matches.iterrows():
    #print(stats2.loc[row['home_team'], 'AttackForce'])
    world_cup_matches.loc[index,'HomeAttack'] = (stats2.loc[row['home_team'], 'AttackForce']) #- statistics.mean(stats2['AttackForce'])) / statistics.stdev(stats2['AttackForce'])
    world_cup_matches.loc[index,'HomeDefence'] = (stats2.loc[row['home_team'], 'DefenseForce']) #- statistics.mean(stats2['DefenseForce'])) / statistics.stdev(stats2['DefenseForce'])
    world_cup_matches.loc[index,'AwayAttack'] = (stats2.loc[row['away_team'], 'AttackForce']) #- statistics.mean(stats2['AttackForce'])) / statistics.stdev(stats2['AttackForce'])
    world_cup_matches.loc[index,'AwayDefence'] = (stats2.loc[row['away_team'], 'DefenseForce']) #- statistics.mean(stats2['DefenseForce'])) / statistics.stdev(stats2['DefenseForce'])
world_cup_matches.head()

['Friendly', 'AFC Asian Cup', 'African Cup of Nations', 'ABCS Tournament', 'FIFA World Cup qualification', 'Gold Cup qualification', 'UEFA Euro qualification', 'Windward Islands Tournament', 'COSAFA Cup', 'Copa América', 'African Cup of Nations qualification', 'African Nations Championship', 'CONIFA European Football Cup', 'Island Games', 'Gold Cup', 'EAFF Championship', 'Oceania Nations Cup qualification', 'CECAFA Cup', 'SAFF Cup', 'Copa América qualification', 'CFU Caribbean Cup qualification', 'Oceania Nations Cup', 'Baltic Cup', 'CONIFA World Football Cup', 'AFC Asian Cup qualification', 'Kirin Cup', "King's Cup", 'UEFA Euro', 'World Unity Cup', 'AFF Championship', 'AFC Challenge Cup', 'UNCAF Cup', 'Confederations Cup', 'CFU Caribbean Cup', 'Intercontinental Cup', 'FIFA World Cup', 'AFF Championship qualification', 'UEFA Nations League']
                          AttackForce  DefenseForce
Team
Canada                       1.035155      2.014207
Bhutan                       0.546951      0.697952
Andorra                      0.340206      1.984217
Kenya                        1.064688      2.322145
Israel                       1.601158      1.647964
Dominican Republic           1.319447      2.336290
Gotland                      3.505107      2.097170
Raetia                       0.770126      0.677473
Brunei                       1.218412      0.907685
Malta                        0.619912      1.165916
Sudan                        0.768657      2.744364
Corsica                      0.532609      2.439127
Peru                         1.746841      2.534478
North Macedonia              2.041710      2.785360
Kazakhstan                   1.244138      1.747190
Suriname                     1.441353      2.059484
Oman                         1.504513      1.971032
Venezuela                    1.143593      1.785686
São Tomé and Príncipe        0.688659      1.166426
United Arab Emirates         1.373617      2.591379
Austria                      1.558353      2.340779
Tuvalu                       1.207347      0.287115
Liechtenstein                0.720738      1.030448
Sierra Leone                 0.813422      1.767455
New Caledonia                1.750051      1.661468
Somaliland                   2.567086      1.298489
Hitra                        1.452290      1.303232
Burundi                      1.644060      2.660244
Comoros                      0.735077      2.139455
Cook Islands                 0.981012      8.154845
...                               ...           ...
Haiti                        1.252967      1.498486
Bulgaria                     1.650704      2.110288
Laos                         0.952483      0.875975
Uruguay                      2.105354      2.015098
Saint Kitts and Nevis        0.705653      1.151123
Georgia                      1.685745      2.278714
Gambia                       0.832731      2.493268
Senegal                      1.919343      3.795229
Botswana                     1.253835      2.578840
Romani people                1.716771      2.038711
Myanmar                      2.142857      0.560000
Guinea                       1.535698      1.876247
Albania                      0.904222      1.542110
Iraq                         1.171662      1.817931
Kosovo                       2.336116      2.398555
Ellan Vannin                 2.106431      1.854782
Somalia                      0.204723      1.762589
Switzerland                  2.760987      3.155042
Western Armenia              3.488698      1.897546
Maldives                     1.695250      1.281884
Bonaire                      0.367879      1.553304
Libya                        1.595852      2.359509
Guernsey                     2.540546      3.701766
Tajikistan                   1.356713      1.436900
Egypt                        1.898768      2.800424
Malaysia                     1.406246      1.645452
Cascadia                     5.666667      1.090909
Central African Republic     1.298907      1.136919
Iraqi Kurdistan              1.848302      6.492447
Ecuador                      1.643628      2.357722

[266 rows x 2 columns]

,home_team,home_score,away_score,away_team,tournament,year,month,day,HomeAttack,HomeDefence,AwayAttack,AwayDefence
36609,Bahrain,1,0,Jordan,Friendly,2015,1,4,1.343923,2.456820,1.391631,2.357554
36610,Iran,1,0,Iraq,Friendly,2015,1,4,1.741084,3.305040,1.171662,1.817931
36611,South Korea,2,0,Saudi Arabia,Friendly,2015,1,4,1.617132,1.989357,1.864505,1.284967
36612,South Africa,1,0,Zambia,Friendly,2015,1,4,1.347449,3.578576,1.306898,3.235983
36613,China PR,4,1,Oman,Friendly,2015,1,5,1.469917,1.591850,1.504513,1.971032

In [17]:
stats2.describe()

       AttackForce  DefenseForce
count   266.000000    266.000000
mean      1.537823      2.038869
std       0.810247      1.075343
min       0.146563      0.287115
25%       1.029401      1.361281
50%       1.387939      1.934722
75%       1.910922      2.455268
max       5.666667      8.712396

In [18]:
for team in wc_teams:
    print(team, "Attack: " + str(stats2.loc[team, 'AttackForce']), "Defense: " + str(stats2.loc[team, 'DefenseForce']))

Russia Attack: 2.0975399891360316 Defense: 1.367703002058528
Brazil Attack: 2.638762703500694 Defense: 8.712396254298977
Australia Attack: 2.4074862164713546 Defense: 2.5390431110108556
Iran Attack: 1.7410843142071957 Defense: 3.3050402908176726
Japan Attack: 2.470089150615758 Defense: 1.9800193256746679
Saudi Arabia Attack: 1.8645052994777882 Defense: 1.2849673569652964
South Korea Attack: 1.617132401904067 Defense: 1.9893570437899306
Egypt Attack: 1.8987678803026862 Defense: 2.800424070456143
Morocco Attack: 2.1045545804169183 Defense: 4.197873648769421
Nigeria Attack: 1.6241110581401077 Defense: 2.477726068449955
Senegal Attack: 1.9193428028134527 Defense: 3.795228765925134
Tunisia Attack: 1.9149727218578487 Defense: 2.0147110774220964
Costa Rica Attack: 1.493339754791466 Defense: 1.319515561380824
Mexico Attack: 1.7499704819723774 Defense: 2.004320004171832
Panama Attack: 1.2135432189056439 Defense: 1.530809919827554
Argentina Attack: 2.2583412611008504 Defense: 2.800420963275008
Colombia Attack: 1.8377599160084146 Defense: 2.9727269135179557
Peru Attack: 1.746841431916185 Defense: 2.5344779226401433
Uruguay Attack: 2.1053537740922184 Defense: 2.0150976109409804
Belgium Attack: 4.040287879303074 Defense: 2.498895880107028
Croatia Attack: 2.5780411525822124 Defense: 2.3430696705768517
Denmark Attack: 1.9340830297468088 Defense: 3.2987616087336686
England Attack: 2.553545768507972 Defense: 3.1625386904342063
France Attack: 2.650758341495184 Defense: 2.1545356863975345
Germany Attack: 2.8359948653539298 Defense: 2.4506111112616016
Iceland Attack: 1.5571170824512557 Defense: 1.3730579403148735
Poland Attack: 2.2304468423771358 Defense: 2.256523729787591
Portugal Attack: 2.6528954410854935 Defense: 2.8557497863059758
Serbia Attack: 2.0812319914295982 Defense: 2.2682038590518947
Spain Attack: 3.3313348278793726 Defense: 2.716951879664001
Sweden Attack: 2.0272853881323427 Defense: 2.62643853147323
Switzerland Attack: 2.7609866229338693 Defense: 3.1550423885639143

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

# essa tabela duplica os jogos, para ter apenas uma variavel alvo: gols
# ela transforma as colunas em time, oponente, gols, fora o resto das variaveis
# ou seja, os gols sao sempre referentes ao "time", contra o "oponente"
# nao existe mais dentro e fora de casa, ja que a tabela foi duplicada
goal_model_data = pd.concat([world_cup_matches[['home_team','away_team', 'HomeAttack', 'HomeDefence', 'AwayAttack', 'AwayDefence', 'home_score']].rename(
            columns={'home_team':'team', 'away_team':'opponent', 'HomeAttack':'att', 'HomeDefence': 'defe', 'AwayAttack': 'away_att', 'AwayDefence': 'away_def', 'home_score':'goals'}),
           world_cup_matches[['away_team','home_team', 'AwayAttack', 'AwayDefence','HomeAttack', 'HomeDefence', 'away_score']].rename(
            columns={'away_team':'team', 'home_team':'opponent', 'AwayAttack':'att', 'AwayDefence': 'defe', 'HomeAttack': 'away_att', 'HomeDefence': 'away_def','away_score':'goals'})])

#print(goal_model_data)
#goal_model_data = goal_model_data.drop(columns=['team', 'opponent'])
# definicao dos parametros, tendo como variavel alvo os gols e o resto como entrada
poisson_model = smf.glm(formula="goals ~ att + defe + away_att + away_def", data=goal_model_data, 
                        family=sm.families.Poisson()).fit()
#poisson_model.predict()
poisson_model.summary()

In [ ]:
def get_team_stats(team, return_df=False):
    #print(stats2)
    attack = stats2.loc[team, 'AttackForce']
    defence = stats2.loc[team, 'DefenseForce']
    
    # teste para influencia da variavel year
    #year = world_cup_matches.loc[team, 'year']
    #print(attack, defence)
    return [attack, defence]

def simulate_goals(team_pred, game, a_team='A Team', b_team='B Team', verbose=False):
    #a_goals = np.argmax(team_pred[0])
    #b_goals = np.argmax(team_pred[1])
    
    #print(a_goals)
    #print(b_goals)
    a_goals = 0
    b_goals = 0
    outcome = 0

    random_event = np.random.random()
    #print(random_event)
    counter = 0


    for index, row in pd.DataFrame(data=game).iterrows():
        for x in range(len(row)):
            counter += row[x]
            
            a_goals = index
            b_goals = x
            
            if counter > random_event:
                break
        if counter > random_event:
            break
    
    if verbose == True:
        #print('Random float: {}'.format(random_event))
        print('{} goals: {}'.format(a_team, str(a_goals)))
        print('{} goals: {}\n'.format(b_team, str(b_goals)))
    
    return a_goals, b_goals

def show_game_summary(game, team_pred, a_team='A Team', b_team='B Team', verbose=False):
    a_team_odds = np.sum(np.tril(game, -1))
    b_team_odds = np.sum(np.triu(game, 1))
    draw_odds = np.sum(np.diag(game))
    
    if verbose == True:
        print('{} chance of Win: {}%'.format(a_team, round(a_team_odds*100, 2)))
        print('{} chance of Win: {}%'.format(b_team, round(b_team_odds*100, 2)))
        print('Odds of a draw: {}%'.format(round(draw_odds*100, 2)))
    
    a_goals, b_goals = simulate_goals(team_pred, game, a_team, b_team, verbose=verbose)
    #print(a_goals, b_goals)
    return a_team_odds, b_team_odds, draw_odds, a_goals, b_goals

# predicao dos gols dos times em uma partida
def team_preds(foot_model, a_team, b_team, max_goals=5, verbose=False):
    a_team_stats = get_team_stats(a_team)
    b_team_stats = get_team_stats(b_team)

    data1 = {'att': a_team_stats[0],
              'defe': a_team_stats[1],
              'away_att': b_team_stats[0], 
              'away_def': b_team_stats[1]
              }
    print(data1)
    
    data2 = {'att': b_team_stats[0],
              'defe': b_team_stats[1],
              'away_att': a_team_stats[0], 
              'away_def': a_team_stats[1]
            }
    print(data2)
        
    a_goals_avg = foot_model.predict(pd.DataFrame(data=data1, index=[1])).values[0]
    b_goals_avg = foot_model.predict(pd.DataFrame(data=data2, index=[1])).values[0]
    #rint(a_goals_avg)
    #rint(b_goals_avg)
    
    lambda_a = a_team_stats[0] * b_team_stats[1]
    lambda_b = b_team_stats[0] * a_team_stats[1]
    
    team_pred = [[poisson.pmf(i, team_avg) for i in range(0, max_goals+1)] for team_avg in [a_goals_avg, b_goals_avg]]
    #print(max(team_pred[0]))
    #print(team_pred[1])
    #game = (np.outer(np.array(team_pred[0]), np.array(team_pred[1])))
    #print(game)
    #show_game_summary(game, a_team, b_team, verbose=verbose)
    return team_pred

# simulacao de uma partida, retornando a matriz que nos interessa
def simulate_match(team_pred, foot_model, a_team, b_team, max_goals=5, verbose=False):
    game = (np.outer(np.array(team_pred[0]), np.array(team_pred[1])))
    show_game_summary(game, team_pred, a_team, b_team, verbose=verbose)
    return game

In [ ]:
team_predz = team_preds(poisson_model, 'Iran', 'Brazil')
game = simulate_match(team_predz, poisson_model, 'Iran', 'Brazil')
#pd.DataFrame(game)
show_game_summary(game, team_predz, 'Iran', 'Brazil', verbose=True)

In [ ]:
pd.DataFrame(game)

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math

def get_numbers_from_array(array):
    nums = []
    for n in array:
        try:
            nums.append(n[0])
        except:
            nums.append(n)
    return nums

# funcao para calcular as metricas do model
# tenho utilizado como base a metrica r2, que e um valor entre 0 e 1, sendo 1 o modelo perfeito
# o maximo que consegui chegar foi 0.21 e alguma coisa, depois de variar os parametros
# o que ainda e muito baixo, mas nao consegui melhorar muito mais infelizmente
# talvez se nossa predicao fosse de vitoria/derrota poderiamos ter um resultado melhor
def model_metrics(dataframe, poisson_model):
    yreal = []
    ypred = []
    team_pred = []
    i = 0
    print(dataframe)
    yreal = list(dataframe['goals'])
    Y = pd.DataFrame(dataframe['goals'])
    X = dataframe.drop(columns=['goals', 'team', 'opponent'])
    res = sm.Poisson(Y.astype(float), X).fit()
    ypred = poisson_model.predict()
    ypred = get_numbers_from_array(ypred)
    print(ypred)
    #for index, row in dataframe.iterrows():
    #    team_pred = team_preds(poisson_model, row['team'], row['opponent'])
        #print(team_pred)
    #    yreal.append(row['goals'])
    #    ypred.append(team_pred[0].index(max(team_pred[0])))
    #print(yreal)
    #print(ypred)
    rms = math.sqrt(mean_squared_error(yreal, ypred))
    r2 = r2_score(yreal, ypred)
    return rms, r2

metrics = model_metrics(goal_model_data, poisson_model)
print(metrics)

In [ ]:
def normalize_test_model(y):
    if y > (14/3):
        return 5
    elif y > (11/3):
        return 4
    elif y > (8/3):
        return 3
    elif y > (4/3):
        return 2
    elif y < (2/3):
        return 0
    else:
        return 1
    
def compare_accuracy(df):
    count1 = 0

    for index, row in df.iterrows():
        if row['predicted'] == row['goals']:
            count1 += 1
        else:
            continue

    print('Poisson Model: {}% accurate'.format((count1 / len(test_model_df))*100))

#print(goal_model_data)
X = goal_model_data.drop(columns=['goals', 'team', 'opponent'])
Y = pd.DataFrame(goal_model_data['goals'])
#print(X)
#print(np.asarray(X))
res = sm.Poisson(Y.astype(float), X).fit()
poisson_y_pred = poisson_model.predict()
#print(poisson_y_pred)
poisson_y_pred = get_numbers_from_array(poisson_y_pred)
print(poisson_y_pred)
ml_data = [poisson_y_pred]

test_model_df = pd.DataFrame(ml_data, 
                             index=['predicted']).transpose()

test_model_df['goals'] = list(goal_model_data['goals'])
test_model_df['predicted'] = test_model_df['predicted'].apply(normalize_test_model)
print(test_model_df)
compare_accuracy(test_model_df)
#goal_model_data.tail()

In [ ]:
team_predz = team_preds(poisson_model, 'Spain', 'Brazil')
game = simulate_match(team_predz, poisson_model, 'Spain', 'Brazil')
#pd.DataFrame(game)
show_game_summary(game, team_predz, 'Spain', 'Brazil', verbose=True)

In [ ]:
def predicao(a_team, b_team, max_goals=5):
    a_team_stats = get_team_stats(a_team)
    b_team_stats = get_team_stats(b_team)
    
    a_att = a_team_stats[0]
    a_def = a_team_stats[1]
    b_att = b_team_stats[0]
    b_def = b_team_stats[1]
    
    a_avg = a_att / b_def
    b_avg = b_att / a_def
    
    print(a_avg)
    print(b_avg)
    
    team_pred = [[poisson_distribution(avg, k) for k in range(0, max_goals+1)] for avg in [a_avg, b_avg]]
    
    return team_pred

def poisson_distribution(avg, k):
    
    result = (math.exp(-avg)*(avg**k)) / math.factorial(k)
    
    return result
    
predicao('Brazil', 'Spain')